CREATE TABLE [dbo].[Inventory_BaseDataLog] (
    [IBDL_LOG_ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [IBDL_IBD_SEQ_ID]         BIGINT          NOT NULL,
    [IBDL_PLANT]              NVARCHAR (15)   NOT NULL,
    [IBDL_SYSTEM]             NVARCHAR (50)   NOT NULL,
    [IBDL_MATERIAL]           NVARCHAR (100)  NOT NULL,
    [IBDL_BOM_NO]             VARCHAR (50)    NOT NULL,
    [IBDL_TYPE]               NVARCHAR (50)   NULL,
    [IBDL_CLAC_TYPE]          CHAR (1)        NULL,
    [IBDL_UNIT]               NVARCHAR (50)   NULL,
    [IBDL_TANK_CAPACITY]      INT             NULL,
    [IBDL_TANK_AMT]           INT             NULL,
    [IBDL_FEED_AMT]           INT             NULL,
    [IBDL_MAX_LIMIT]          INT             NULL,
    [IBDL_BOOKING_LIMIT]      INT             NULL,
    [IBDL_TRANSFER_PARA]      DECIMAL (18, 2) NULL,
    [IBDL_NUIT_TRANSFER_PARA] DECIMAL (18, 2) NULL,
    [IBDL_InitialStock]       DECIMAL (18, 2) NULL,
    [IBDL_MEMO]               NVARCHAR (MAX)  CONSTRAINT [DF__Inventory__IBDL___7ECCBBD3] DEFAULT ('') NULL,
    [IBDL_WATER_VOL]          INT             NULL,
    [IBDL_FAB_UNIT]           NVARCHAR (50)   NULL,
    [IBDL_PackingUnit]        NVARCHAR (50)   CONSTRAINT [DF__Inventory__IBDL___7CE47361] DEFAULT ('') NULL,
    [IBDL_AUTO_ORDER]         CHAR (1)        NULL,
    [IBDL_ONLINE]             CHAR (1)        NULL,
    [IBDL_TAG_SITE]           INT             NULL,
    [IBDL_CylinderQuantity]   INT             NULL,
    [IBDL_MaxValue]           DECIMAL (18, 2) NULL,
    [IBDL_MinValue]           DECIMAL (18, 2) NULL,
    [IBDL_DelayDay]           INT             NULL,
    [IBDL_UPD_DATETIME]       DATETIME        CONSTRAINT [DF_Inventory_BaseDataLog_IBDL_UPD_DATETIME] DEFAULT ((0)) NULL,
    [IBDL_UPD_USER]           VARCHAR (50)    NULL,
    CONSTRAINT [PK_Inventory_BaseDataLog] PRIMARY KEY CLUSTERED ([IBDL_LOG_ID] ASC)
);

