CREATE TABLE [dbo].[LOCAL_LIST] (
    [LIST_NO]     VARCHAR (50) NULL,
    [ASN_NO]      VARCHAR (50) NULL,
    [MATNO]       VARCHAR (50) NULL,
    [MATNONAME]   VARCHAR (50) NULL,
    [INXUNIT]     VARCHAR (50) NULL,
    [PLANT]       VARCHAR (50) NULL,
    [VENDORCODE]  VARCHAR (50) NULL,
    [VENDORNAME]  VARCHAR (50) NULL,
    [CARCOMPNO]   VARCHAR (50) NULL,
    [CARCOMPNAME] VARCHAR (50) NULL,
    [CAR_NO]      VARCHAR (50) NULL,
    [NET_WEIGHT]  VARCHAR (50) NULL,
    [IN_WEIGHT]   VARCHAR (50) NULL,
    [OUT_WEIGHT]  VARCHAR (50) NULL,
    [IN_TIME]     VARCHAR (50) NULL,
    [OUT_TIME]    VARCHAR (50) NULL,
    [DATE]        VARCHAR (50) NULL,
    [OUT_DATE]    VARCHAR (50) NULL,
    [UPDATE_TIME] DATETIME     CONSTRAINT [DF_LOCAL_LIST_UPDATE_TIME] DEFAULT (getdate()) NULL
);

