CREATE TABLE [dbo].[ORG] (
    [SEQ_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [ORG_ID]      VARCHAR (50)  NOT NULL,
    [ORG_PLANT]   VARCHAR (50)  NOT NULL,
    [ORG_PLANT2]  VARCHAR (50)  NULL,
    [ORG_MVT]     VARCHAR (50)  NULL,
    [ORG_SHOP]    VARCHAR (50)  NOT NULL,
    [ORG_NAME]    NVARCHAR (50) NULL,
    [UPDATE_USER] VARCHAR (50)  NULL,
    [UPDATE_TIME] DATETIME      NULL,
    CONSTRAINT [PK_ORG] PRIMARY KEY CLUSTERED ([SEQ_ID] ASC)
);

