CREATE TABLE [dbo].[SDP_VENDOR] (
    [SV_SEQ_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [SV_VENDOR_NAME] NVARCHAR (50) NULL,
    [SV_VENDOR_CODE] NVARCHAR (50) NULL,
    [SV_VENDOR_TEL]  NVARCHAR (50) NULL
);

