CREATE TABLE [dbo].[SDP_ORDER_Log] (
    [SOL_SEQ_ID] INT            IDENTITY (1, 1) NOT NULL,
    [SOM_ID]     INT            NOT NULL,
    [SOL_TYPE]   VARCHAR (50)   NOT NULL,
    [SOL_ErrMsg] NVARCHAR (250) CONSTRAINT [DF_SDP_ORDER_LOG_SOL_ErrMsg] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_SDP_ORDER_LOG] PRIMARY KEY CLUSTERED ([SOL_SEQ_ID] ASC)
);

