CREATE TABLE [dbo].[TAG_MAPPING] (
    [TM_SEQ_ID]      INT             IDENTITY (1, 1) NOT NULL,
    [TM_TYPE_ID]     INT             NOT NULL,
    [TM_TAG_NAME]    VARCHAR (100)   NOT NULL,
    [TM_TAG_DESC]    VARCHAR (100)   NULL,
    [TM_TAG_SITE]    INT             NOT NULL,
    [TM_TAG1_ID]     VARCHAR (200)   NULL,
    [TM_TAG_PAIR1]   VARCHAR (100)   NULL,
    [TM_TAG_PAIR2]   VARCHAR (100)   NULL,
    [TM_TAG_PAIR3]   VARCHAR (100)   NULL,
    [TM_TAG_DEFAULT] DECIMAL (18, 4) NULL,
    [TM_TYPE_OF]     INT             NULL,
    [TM_Sort]        INT             CONSTRAINT [DF_TAG_MAPPING_TM_Sort] DEFAULT ((99)) NULL,
    [TM_UPDATE_USER] VARCHAR (50)    NULL,
    [TM_UPDATE_TIME] DATETIME        NULL,
    CONSTRAINT [PK_TAG_MAPPING_1] PRIMARY KEY CLUSTERED ([TM_TAG_NAME] ASC)
);

