
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<由物管db取得最新訂單資訊，每分鐘更新>
-- =============================================
CREATE PROCEDURE [dbo].[Insert_SDP_Temp] 
as
BEGIN
Delete SDP_VW_SRM_CALLED_ORDERS_GCIC_TEMP
Delete SDP_VW_ASN_DATA_GCIC

Insert Into [dbo].[SDP_VW_SRM_CALLED_ORDERS_GCIC_TEMP] ( [CALLED_NO]
      ,[ACTUAL_ARRIVAL_DATE]
      ,[ACTUAL_ARRIVAL_QTY]
      ,[ARRIVAL_DATE]
      ,[CALLED_DATE]
      ,[CANCEL_REASON]
      ,[CLOSE_ASN_QTY]
      ,[CLOSE_FLAG]
      ,[CLOSE_REASON]
      ,[CONTACT_TELNO]
      ,[CONTACT_WINDOW]
      ,[CREATE_BY]
      ,[CREATE_DATE]
      ,[DESCRIPTION]
      ,[ERROR_MSG]
      ,[GUID]
      ,[MATERIAL_NO]
      ,[MATGROUP]
      ,[MTD_ARRIVAL_QTY]
      ,[NO_ARRIVAL_QTY]
      ,[PLANT]
      ,[PO_LINE]
      ,[PO_NO]
      ,[REMARKS]
      ,[REVISION]
      ,[SHIP_QTY]
      ,[STATUS]
      ,[TRX_QTY]
      ,[UNIT]
      ,[VENDOR_ARRIVAL_DATE]
      ,[VENDOR_CODE]
      ,[VENDOR_CONFIRM_DATE]
      ,[VENDOR_NAME]
      ,[VENDOR_REMARK]
      ,[VENDOR_SHIP_DATE]
      ,[UPDATE_DATE]
      ,[SOURCE])
	  select  [CALLED_NO]
      ,[ACTUAL_ARRIVAL_DATE]
      ,[ACTUAL_ARRIVAL_QTY]
      ,[ARRIVAL_DATE]
      ,[CALLED_DATE]
      ,[CANCEL_REASON]
      ,[CLOSE_ASN_QTY]
      ,[CLOSE_FLAG]
      ,[CLOSE_REASON]
      ,[CONTACT_TELNO]
      ,[CONTACT_WINDOW]
      ,[CREATE_BY]
      ,[CREATE_DATE]
      ,[DESCRIPTION]
      ,[ERROR_MSG]
      ,[GUID]
      ,[MATERIAL_NO]
      ,[MATGROUP]
      ,[MTD_ARRIVAL_QTY]
      ,[NO_ARRIVAL_QTY]
      ,[PLANT]
      ,[PO_LINE]
      ,[PO_NO]
      ,[REMARKS]
      ,[REVISION]
      ,[SHIP_QTY]
      ,[STATUS]
      ,[TRX_QTY]
      ,[UNIT]
      ,[VENDOR_ARRIVAL_DATE]
      ,[VENDOR_CODE]
      ,[VENDOR_CONFIRM_DATE]
      ,[VENDOR_NAME]
      ,[VENDOR_REMARK]
      ,[VENDOR_SHIP_DATE]
      ,[UPDATE_DATE]
      ,[SOURCE]
 	  from [IIMC_ORACLE_SERVER]..[AP_SDP].SDP_VW_SRM_CALLED_ORDERS_IIMC


INSERT INTO [dbo].[SDP_VW_ASN_DATA_GCIC]
           ([CALLED_NO]
           ,[ASN_NO]
           ,[CAR_NO]
           ,[IMPORT_NO]
           ,[INVOICE_DATE]
           ,[MATERIAL_NO]
           ,[PLANT]
           ,[SHIP_QTY]
           ,[TOT_BOXES]
           ,[TOT_PLATE]
           ,[TRANS_TYPES]
           ,[UPL_LOT]
           ,[UPL_PALLET]
           ,[UPL_PO_LINE]
           ,[UPL_PO_NO]
           ,[VDR_SHIPPING_NO]
           ,[VENDOR_CODE]
           ,[VENDOR_NAME])
	SELECT distinct [CALLED_NO]
		  ,[ASN_NO]
		  ,[CAR_NO]
		  ,[IMPORT_NO]
	  ,[INVOICE_DATE]
           ,[MATERIAL_NO]
           ,[PLANT]
           ,[SHIP_QTY]
           ,[TOT_BOXES]
           ,[TOT_PLATE]
           ,[TRANS_TYPES]
           ,[UPL_LOT]
           ,[UPL_PALLET]
           ,[UPL_PO_LINE]
           ,[UPL_PO_NO]
           ,[VDR_SHIPPING_NO]
           ,[VENDOR_CODE]
           ,[VENDOR_NAME]
	  FROM [IIMC_ORACLE_SERVER]..AP_SDP.SDP_VW_ASN_DATA_IIMC

END
