




-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	叫料單依地磅資訊自動結案
-- =============================================
CREATE PROCEDURE [dbo].[sp_AutoOrderClosed]
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @CalcDate AS DATE=GETDATE()

	--SELECT CONVERT(varchar(10),@CalcDate,111) 
	
	UPDATE SOM
	SET [SOM_STATUS]='Closed',[SOM_CLOSE_ID]=99,[SOM_CLOSE_REMARK]='IIMC自動結案'
	--SELECT SEQ_ID,FM.[PLANT], FM.[INXUNIT],FM.[MATNONAME]--, CONVERT(date,LL.[DATE],120),CONVERT(date,SDP.VENDOR_ARRIVAL_DATE,111)
	FROM (SELECT * FROM [dbo].[SDP_Order_Master] WHERE [SOM_STATUS]='SENT') SOM 
	INNER JOIN (SELECT * FROM SDP_VW_SRM_CALLED_ORDERS_GCIC UNION SELECT * FROM SDP_VW_SRM_CALLED_ORDERS_GCIC_ALLOCATE) SDP  ON SOM.SOM_SDP_NO=SDP.CALLED_NO 
	INNER JOIN [dbo].[Fill_Mapping] FM ON SOM.IBD_SEQ_ID=FM.IBD_SEQ_ID
	INNER JOIN (SELECT * FROM [LOCAL_LIST] WHERE [DATE]=CONVERT(varchar(10),@CalcDate,111) AND [NET_WEIGHT]<>'(null)' ) LL ON FM.[PLANT]=LL.[PLANT] AND FM.[INXUNIT]=LL.[INXUNIT] AND FM.[MATNONAME]=LL.[MATNONAME]
	AND CONVERT(date,LL.[DATE],120) =CONVERT(date,SDP.VENDOR_ARRIVAL_DATE,111)
	

	--使用地磅ASN結案
	UPDATE SOM
	SET [SOM_STATUS]='Closed',[SOM_CLOSE_ID]=99,[SOM_CLOSE_REMARK]='IIMC自動結案ASN'
	--SELECT SOM.*
	FROM (SELECT * FROM [dbo].[SDP_Order_Master] WHERE [SOM_STATUS]='SENT') SOM 
	INNER JOIN SDP_VW_SRM_CALLED_ORDERS_GCIC SDP ON SOM.SOM_SDP_NO=SDP.CALLED_NO
	INNER JOIN [LOCAL_LIST] LL ON SDP.ASN=LL.ASN_NO


	
END
