


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<每日執行，將昨日入料自動結案，CHEMICAL 比對ASN 有入料及結案，GAS 比對ASN及數量，皆符合才結案>
-- =============================================
 CREATE PROCEDURE [dbo].[sp_SDP_Order_Master_AutoClose]
	@CalcDate AS DATE --重新指定運算日期
AS
BEGIN
--DECLARE @CalcDate AS DATE =''
DECLARE @StartDate AS DATETIME
DECLARE @EndDate AS DATETIME

IF (@CalcDate<>'')--如有指定日期，則以指定日期計算
	SET @StartDate =  @CalcDate ;
ELSE
	SELECT @StartDate = CONVERT(VARCHAR(10),DATEADD(D,-1,GETDATE()),111)

SET @EndDate= DATEADD(D,1,DATEADD(s,-1,DATEADD(D,1,@StartDate)))

--SELECT @CalcDate,@StartDate,@EndDate

--CHEMICAL
--SDP 叫料(KEY=廠別、asn、入料日期)
UPDATE A SET SOM_STATUS='Closed' ,A.SOM_CLOSE_ID=99,A.SOM_CLOSE_REMARK='自動結案' FROM SDP_Order_Master A 
--SELECT SOM_SDP_NO AS '單號',A.SOM_BOM AS '廠務叫料',D.MTRL_NO AS '廠務收料',convert(varchar,B.VENDOR_ARRIVAL_DATE, 112) AS '廠商到貨日',convert(varchar,D.OPE_DATE, 112) AS '收料日',B.SHIP_QTY,B.ASN AS '叫料ASN',D.ASN_NO AS '收料ASN' FROM SDP_Order_Master A 
INNER JOIN SDP_VW_SRM_CALLED_ORDERS_GCIC B 
ON A.SOM_SDP_NO=B.CALLED_NO AND A.SOM_STATUS='SENT' AND B.MATGROUP LIKE'3400%' AND B.VENDOR_ARRIVAL_DATE BETWEEN @StartDate AND @EndDate
INNER JOIN Material_Receipt D ON A.SOM_PLANT=D.PLANT AND B.ASN=D.ASN_NO  AND convert(varchar,B.VENDOR_ARRIVAL_DATE, 112) =convert(varchar,D.OPE_DATE, 112)

--廠內調撥(KEY=廠別、料號、入料日期)
UPDATE A SET SOM_STATUS='Closed' ,A.SOM_CLOSE_ID=99,A.SOM_CLOSE_REMARK='自動結案' FROM SDP_Order_Master A 
--SELECT SOM_SDP_NO AS '單號',A.SOM_BOM AS '廠務叫料',D.MTRL_NO AS '廠務收料',convert(varchar,B.VENDOR_ARRIVAL_DATE, 112) AS '廠商到貨日',convert(varchar,D.OPE_DATE, 112) AS '收料日',B.SHIP_QTY,B.ASN AS '叫料ASN',D.ASN_NO AS '收料ASN' FROM SDP_Order_Master A 
INNER JOIN SDP_VW_SRM_CALLED_ORDERS_GCIC_ALLOCATE B 
ON A.SOM_SDP_NO=B.CALLED_NO AND A.SOM_STATUS='SENT' AND B.MATGROUP LIKE'3400%' AND B.VENDOR_ARRIVAL_DATE BETWEEN @StartDate AND @EndDate
INNER JOIN Material_Receipt D ON A.SOM_PLANT=D.PLANT AND A.SOM_BOM=D.MTRL_NO AND convert(varchar,B.VENDOR_ARRIVAL_DATE, 112) =convert(varchar,D.OPE_DATE, 112)

--GAS
UPDATE A SET SOM_STATUS='Closed' ,A.SOM_CLOSE_ID=99,A.SOM_CLOSE_REMARK='自動結案' FROM SDP_Order_Master A 
--SELECT SOM_SDP_NO,A.SOM_BOM,VENDOR_ARRIVAL_DATE,B.SHIP_QTY,B.ASN,D.ASN_NO FROM SDP_Order_Master A 
LEFT JOIN (SELECT * FROM SDP_VW_SRM_CALLED_ORDERS_GCIC UNION SELECT * FROM SDP_VW_SRM_CALLED_ORDERS_GCIC_ALLOCATE) B ON A.SOM_SDP_NO=B.CALLED_NO 
LEFT JOIN Inventory_BaseData C ON B.MATERIAL_NO=C.IBD_BOM_NO AND B.PLANT=C.IBD_PLANT
INNER JOIN (
SELECT  [PLANT],[ASN_NO],COUNT(*) AS CON FROM [Material_Receipt]
  WHERE [MTRL_GRP]='氣體' AND [WORK_TYPE]='鋼瓶入料' AND [OPE_DATE] BETWEEN @StartDate AND @EndDate
  GROUP BY [PLANT],[MTRL_GRP],[WORK_TYPE],[ASN_NO]) D
   ON A.SOM_PLANT=D.PLANT AND B.ASN=D.ASN_NO AND B.SHIP_QTY=D.CON*C.IBD_TRANSFER_PARA
WHERE A.SOM_STATUS='SENT' AND C.IBD_SYSTEM='GMSG' AND B.VENDOR_ARRIVAL_DATE BETWEEN @StartDate AND @EndDate

--GAS(槽車)
UPDATE A SET SOM_STATUS='Closed' ,A.SOM_CLOSE_ID=99,A.SOM_CLOSE_REMARK='自動結案' FROM SDP_Order_Master A 
--SELECT SOM_SDP_NO,A.SOM_BOM,VENDOR_ARRIVAL_DATE,B.SHIP_QTY,B.ASN,D.ASN_NO,C.IBD_TRANSFER_PARA FROM SDP_Order_Master A 
LEFT JOIN SDP_VW_SRM_CALLED_ORDERS_GCIC B ON A.SOM_SDP_NO=B.CALLED_NO 
LEFT JOIN Inventory_BaseData C ON a.IBD_SEQ_ID=c.IBD_SEQ_ID AND B.PLANT=C.IBD_PLANT
INNER JOIN (
SELECT  [PLANT],[ASN_NO],COUNT(*) AS CON FROM [Material_Receipt]
  WHERE [MTRL_GRP]='氣體' AND [WORK_TYPE]='鋼瓶入料' AND [OPE_DATE] BETWEEN @StartDate AND @EndDate
  GROUP BY [PLANT],[MTRL_GRP],[WORK_TYPE],[ASN_NO]) D 
   ON A.SOM_PLANT=D.PLANT AND B.ASN=D.ASN_NO --AND B.SHIP_QTY=D
WHERE A.SOM_STATUS='SENT' AND C.IBD_SYSTEM='GMSG' AND C.IBD_TRANSFER_PARA>3000 AND B.VENDOR_ARRIVAL_DATE BETWEEN @StartDate AND @EndDate

END


