
CREATE PROCEDURE [dbo].[sp_SDP_ORDER_TO_HIS]
AS
BEGIN
    INSERT INTO SDP_VW_SRM_CALLED_ORDERS_GCIC_HIS_ALLOCATE
	SELECT S.* FROM SDP_VW_SRM_CALLED_ORDERS_GCIC_ALLOCATE S LEFT JOIN SDP_VW_SRM_CALLED_ORDERS_GCIC_HIS_ALLOCATE D
	ON S.CALLED_NO=D.CALLED_NO AND S.UPDATE_DATE=D.UPDATE_DATE
	WHERE D.UPDATE_DATE IS NULL
END

 






